"""add auth roles

Revision ID: a1a24242c4d8_add_auth_roles
Revises: a1a24242c4d8
Create Date: 2025-12-01 10:45:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a1a24242c4d8_add_auth_roles"
down_revision: Union[str, Sequence[str], None] = "a1a24242c4d8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # 为 users 表添加认证字段（先允许为空）
    op.add_column("users", sa.Column("is_active", sa.Boolean(), nullable=True))
    op.add_column("users", sa.Column("is_superuser", sa.Boolean(), nullable=True))

    # 设置默认值（SQLite 兼容）
    op.execute(sa.text("UPDATE users SET is_active = 1 WHERE is_active IS NULL"))
    op.execute(sa.text("UPDATE users SET is_superuser = 0 WHERE is_superuser IS NULL"))

    # 创建新表（SQLite ALTER COLUMN 限制的变通方案）
    op.create_table(
        "roles",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("is_system", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_roles_name"), "roles", ["name"], unique=True)

    # 创建 permissions 表
    op.create_table(
        "permissions",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("resource", sa.String(length=100), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_permissions_name"), "permissions", ["name"], unique=True)
    op.create_index(op.f("ix_permissions_code"), "permissions", ["code"], unique=True)

    # 创建 role_permissions 关联表
    op.create_table(
        "role_permissions",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("permission_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permissions.id"],
        ),
        sa.PrimaryKeyConstraint("role_id", "permission_id"),
    )

    # 创建 user_roles 关联表
    op.create_table(
        "user_roles",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "role_id"),
    )

    # 插入默认角色（SQLite 兼容）
    op.execute(
        sa.text("""
            INSERT INTO roles (id, name, description, is_system, created_at, updated_at)
            VALUES
                (1, 'user', '普通用户角色', 1, datetime('now'), datetime('now')),
                (2, 'admin', '管理员角色', 1, datetime('now'), datetime('now'))
        """)
    )

    # 插入基础权限
    op.execute(
        sa.text("""
            INSERT INTO permissions (id, name, code, description, resource, action, created_at)
            VALUES
                (1, '查看用户', 'user.view', '查看用户信息', 'user', 'view', datetime('now')),
                (2, '创建用户', 'user.create', '创建新用户', 'user', 'create', datetime('now')),
                (3, '编辑用户', 'user.edit', '编辑用户信息', 'user', 'edit', datetime('now')),
                (4, '删除用户', 'user.delete', '删除用户', 'user', 'delete', datetime('now')),
                (5, '查看角色', 'role.view', '查看角色信息', 'role', 'view', datetime('now')),
                (6, '创建角色', 'role.create', '创建新角色', 'role', 'create', datetime('now')),
                (7, '编辑角色', 'role.edit', '编辑角色信息', 'role', 'edit', datetime('now')),
                (8, '删除角色', 'role.delete', '删除角色', 'role', 'delete', datetime('now'))
        """)
    )

    # 为 admin 角色分配所有权限
    op.execute(
        sa.text("""
            INSERT INTO role_permissions (role_id, permission_id, created_at)
            SELECT 2, id, datetime('now') FROM permissions
        """)
    )

    # 为 user 角色分配查看权限
    op.execute(
        sa.text("""
            INSERT INTO role_permissions (role_id, permission_id, created_at)
            SELECT 1, id, datetime('now')
            FROM permissions
            WHERE code IN ('user.view', 'role.view')
        """)
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # 删除关联表
    op.drop_table("user_roles")
    op.drop_table("role_permissions")

    # 删除权限表和角色表
    op.drop_index(op.f("ix_permissions_code"), table_name="permissions")
    op.drop_index(op.f("ix_permissions_name"), table_name="permissions")
    op.drop_table("permissions")

    op.drop_index(op.f("ix_roles_name"), table_name="roles")
    op.drop_table("roles")

    # 删除用户表的新字段
    op.drop_column("users", "is_superuser")
    op.drop_column("users", "is_active")

    # ### end Alembic commands ###
